### ISSUE TITLE
[Powershell] zoxide Does Not Escape Paths

### ISSUE THREAD

**Issue by ditsuke** [ajeetdsouza/zoxide#312]
## Problem
Powershell requires escaping special characters even if they're enclosed in single quotes. So calling `Set-Location` on, say `'D:\test\[foo] bar\'` will fail like:
```
Set-Location : Cannot find path 'test/[foo] bar' because it does not exist.
At line:1 char:1
+ Set-Location 'test/[foo] bar'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (test/[foo] bar:String) [Set-Location], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
```
![image](https://user-images.githubusercontent.com/72784348/145708344-028a19fc-1472-4fa1-bd5d-1655ac1fdc01.png)

## Solution
Path passed to Set-Location should be escaped:

![image](https://user-images.githubusercontent.com/72784348/145708313-3effd0a0-ea95-4bcf-a970-e13258930c9a.png)

**Comment by TeamDman** [comment]
I fixed this by adjusting my profile to override the `__zoxide_cd`

```pwsh
function cd {
    z @args
}

Invoke-Expression (& { (zoxide init powershell | Out-String) })

function global:__zoxide_cd($dir, $literal) {
    # we need to override this so it doesn't pass -LiteralPath
    # https://github.com/ajeetdsouza/zoxide/blob/d99d82f141106c5c9e32fe75ec7695a43b3fcadc/templates/powershell.txt#L29C1-L46C2
    $dir = Set-Location $dir -Passthru -ErrorAction Stop
}
```

Without overriding the function, I got

```
❯ ls
a[]b
❯ cd '.\a`[`]b\'
Set-Location:
Line |
  29 |          Set-Location -LiteralPath $dir -Passthru -ErrorAction Stop
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '.\a`[`]b\' because it does not exist.
```

Looks like it from here at least is always passed `$true` so idk the consequences of changing that but it's working for now

https://github.com/ajeetdsouza/zoxide/blob/d99d82f141106c5c9e32fe75ec7695a43b3fcadc/templates/powershell.txt#L102-L124

**Comment by ajeetdsouza** [comment]
What is the actual name of your directory?

**Comment by TeamDman** [comment]
the problem reproduced for me using a dir named `a[]b`

**Comment by evanjs** [comment]
@TeamDman thank you, that got me on the right track re fixing the issue on my end.

It might have been inferred from the original issue, but `[]` alone is not the only problem.
The aforementioned approach does not work for, say, a path that contains single quotes (`'`)

Using `-LiteralPath` _and_ enclosing the directory with double quotes seems to resolve my issue
Since `"` is not a valid character for filenames on Windows, this **_should_** be fine, then..?

```ps1
# Ensure zoxide properly escapes paths
# See also: https://github.com/ajeetdsouza/zoxide/issues/312#issuecomment-2576555164
function global:__zoxide_cd($dir, $literal) {
    # Enclose the directory with dobule quotes to ensure special characters are escaped when necessary
    $dir = Set-Location -LiteralPath "$dir" -Passthru -ErrorAction Stop
}
```

**Comment by sharpchen** [comment]
EDIT: never mind I think it's pwsh's problem

<details>
<summary>never mind</summary>

@ajeetdsouza this still persist on `zoxide 0.9.9` in some cases.

Reproduction:

```ps1
New-Item -ItemType Directory -Path "foo - bar(123-456)[foo]"
cd -LiteralPath '.\foo - bar(123-456)[foo]'
cd ..
z -
```

```console
Set-Location:
Line |
  38 |              Set-Location -Path $dir -Passthru -ErrorAction Stop
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\user\foo - bar(123-456)[foo]' because it does not exist.
```

<details>
<summary>psversion</summary>

```console
Name                           Value
----                           -----
PSVersion                      7.6.1
PSEdition                      Core
GitCommitId                    7.6.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.4
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

</details>

</details>
